"""initial tracker schema

Revision ID: 001
Revises:
Create Date: 2026-09-30 15:02:36.779444

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("movie_id", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("cinema_id", sa.Text(), nullable=False),
        sa.Column("cinema", sa.Text(), nullable=False),
        sa.Column("room_name", sa.Text(), nullable=False),
        sa.Column("room_key", sa.Text(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("session_time", sa.Time(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("format", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("purchase_url", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "movie_id",
            "cinema_id",
            "room_key",
            "session_date",
            "session_time",
            name="uq_session_identity",
        ),
    )
    op.create_table(
        "watches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("movie_title", sa.Text(), nullable=False),
        sa.Column("providers", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("cinema", sa.Text(), nullable=True),
        sa.Column("room", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "poll_interval_minutes", sa.Integer(), server_default=sa.text("15"), nullable=False
        ),
        sa.Column("next_poll_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("poll_interval_minutes > 0", name="ck_watches_positive_interval"),
        sa.CheckConstraint(
            "providers IS NULL OR cardinality(providers) > 0", name="ck_watches_providers"
        ),
        sa.CheckConstraint("revision >= 1", name="ck_watches_positive_revision"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_watches_due",
        "watches",
        ["next_poll_at"],
        unique=False,
        postgresql_where=sa.text("enabled IS true"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("key", sa.LargeBinary(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint("attempts >= 0", name="ck_outbox_attempts"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "topic", name="uq_outbox_session_topic"),
    )
    op.create_index(
        "ix_outbox_pending",
        "outbox",
        ["created_at", "id"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "watch_provider_targets",
        sa.Column("watch_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("movie_id", sa.Text(), nullable=True),
        sa.Column("resolution_status", sa.String(length=32), nullable=False),
        sa.Column("last_resolution_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_fetch_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_successful_fetch_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_fetch_error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(resolution_status = 'resolved' AND movie_id IS NOT NULL) OR (resolution_status IN ('pending_not_found', 'pending_source_error', 'pending_ambiguous') AND movie_id IS NULL)",
            name="ck_target_resolution",
        ),
        sa.ForeignKeyConstraint(["watch_id"], ["watches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("watch_id", "provider"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watch_provider_targets")
    op.drop_index(
        "ix_outbox_pending", table_name="outbox", postgresql_where=sa.text("published_at IS NULL")
    )
    op.drop_table("outbox")
    op.drop_index(
        "ix_watches_due", table_name="watches", postgresql_where=sa.text("enabled IS true")
    )
    op.drop_table("watches")
    op.drop_table("sessions")
    # ### end Alembic commands ###
